name: Simple CI Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to get your code onto the runner

      - name: Set up Node.js (if your project uses Node)
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify the Node.js version

      - name: Install Dependencies
        run: npm install # Or 'yarn install', 'pip install -r requirements.txt', etc.

      - name: Run Tests
        run: npm test # Or 'yarn test', 'pytest', etc.

      - name: Lint Code (Example)
        run: npm run lint || true # Example: run lint, '|| true' makes it not fail the workflow if linting has warnings
